
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - bms-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bms-net

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/
    networks:
      - bms-net

  bms-service-discovery:
    build: ./bms-service-discovery
    ports:
      - "8761:8761"
    networks:
      - bms-net

  bms-api-gateway-service:
    build: ./bms-api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - bms-service-discovery
    networks:
      - bms-net

  bms-user-service:
    build: ./bms-user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - bms-net

  bms-movie-service:
    build: ./bms-movie-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - bms-net

  bms-booking-service:
    build: ./bms-booking-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - kafka
    networks:
      - bms-net

  bms-messaging-service:
    build: ./bms-messaging-service
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
      - kafka
    networks:
      - bms-net

  bms-payment-service:
    build: ./bms-payment-service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
      - kafka
    networks:
      - bms-net

  bms-ui:
    build:
      context: ./bms-ui
    ports:
      - "4200:80"
    container_name: bms-ui
    depends_on:
      - bms-api-gateway-service
    networks:
      - bms-net

networks:
   bms-net:
     driver: bridge

volumes:
  mongo_data: